# coding: utf-8

"""
    Product and Store Management API

    A simple API for managing products and stores with basic CRUD operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.store import Store

class TestStore(unittest.TestCase):
    """Store unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Store:
        """Test Store
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Store`
        """
        model = Store()
        if include_optional:
            return Store(
                name = 'Downtown Electronics',
                location = '123 Main St, New York, NY',
                phone = '+1-202-555-0173',
                id = '987f6543-a21b-34c5-d678-098765432100'
            )
        else:
            return Store(
                name = 'Downtown Electronics',
                location = '123 Main St, New York, NY',
        )
        """

    def testStore(self):
        """Test Store"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
