# coding: utf-8

"""
    Product and Store Management API

    A simple API for managing products and stores with basic CRUD operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.product_input import ProductInput

class TestProductInput(unittest.TestCase):
    """ProductInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInput:
        """Test ProductInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInput`
        """
        model = ProductInput()
        if include_optional:
            return ProductInput(
                name = 'Apple iPhone 15',
                description = 'Latest model with A16 Bionic chip.',
                price = 999.99,
                quantity = 50,
                category = 'Electronics'
            )
        else:
            return ProductInput(
                name = 'Apple iPhone 15',
                price = 999.99,
        )
        """

    def testProductInput(self):
        """Test ProductInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
