# coding: utf-8

"""
    Product and Store Management API

    A simple API for managing products and stores with basic CRUD operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.store_input import StoreInput

class TestStoreInput(unittest.TestCase):
    """StoreInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreInput:
        """Test StoreInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoreInput`
        """
        model = StoreInput()
        if include_optional:
            return StoreInput(
                name = 'Downtown Electronics',
                location = '123 Main St, New York, NY',
                phone = '+1-202-555-0173'
            )
        else:
            return StoreInput(
                name = 'Downtown Electronics',
                location = '123 Main St, New York, NY',
        )
        """

    def testStoreInput(self):
        """Test StoreInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
