# coding: utf-8

"""
    Product and Store Management API

    A simple API for managing products and stores with basic CRUD operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stores_api import StoresApi


class TestStoresApi(unittest.TestCase):
    """StoresApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StoresApi()

    def tearDown(self) -> None:
        pass

    def test_stores_get(self) -> None:
        """Test case for stores_get

        List all stores
        """
        pass

    def test_stores_id_delete(self) -> None:
        """Test case for stores_id_delete

        Delete a store
        """
        pass

    def test_stores_id_get(self) -> None:
        """Test case for stores_id_get

        Get store details
        """
        pass

    def test_stores_id_put(self) -> None:
        """Test case for stores_id_put

        Update a store
        """
        pass

    def test_stores_post(self) -> None:
        """Test case for stores_post

        Create a new store
        """
        pass


if __name__ == '__main__':
    unittest.main()
