# coding: utf-8

"""
    Product and Store Management API

    A simple API for managing products and stores with basic CRUD operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_products_get(self) -> None:
        """Test case for products_get

        List all products
        """
        pass

    def test_products_id_delete(self) -> None:
        """Test case for products_id_delete

        Delete a product
        """
        pass

    def test_products_id_get(self) -> None:
        """Test case for products_id_get

        Get product details
        """
        pass

    def test_products_id_put(self) -> None:
        """Test case for products_id_put

        Update a product
        """
        pass

    def test_products_post(self) -> None:
        """Test case for products_post

        Create a new product
        """
        pass


if __name__ == '__main__':
    unittest.main()
