# coding: utf-8

"""
    Library Management API

    API cho ứng dụng quản lý thư viện.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ly_danh_sch_sch200_response_inner import LYDanhSChSCh200ResponseInner

class TestLYDanhSChSCh200ResponseInner(unittest.TestCase):
    """LYDanhSChSCh200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LYDanhSChSCh200ResponseInner:
        """Test LYDanhSChSCh200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LYDanhSChSCh200ResponseInner`
        """
        model = LYDanhSChSCh200ResponseInner()
        if include_optional:
            return LYDanhSChSCh200ResponseInner(
                id = '',
                title = '',
                author = '',
                year = 1.337
            )
        else:
            return LYDanhSChSCh200ResponseInner(
        )
        """

    def testLYDanhSChSCh200ResponseInner(self):
        """Test LYDanhSChSCh200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
