# coding: utf-8

"""
    Library Management API

    API cho ứng dụng quản lý thư viện.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.th_msch_mi201_response import ThMSChMI201Response

class TestThMSChMI201Response(unittest.TestCase):
    """ThMSChMI201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThMSChMI201Response:
        """Test ThMSChMI201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThMSChMI201Response`
        """
        model = ThMSChMI201Response()
        if include_optional:
            return ThMSChMI201Response(
                id = '',
                title = '',
                author = '',
                year = 1.337
            )
        else:
            return ThMSChMI201Response(
        )
        """

    def testThMSChMI201Response(self):
        """Test ThMSChMI201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
