# coding: utf-8

"""
    Library Management API

    API cho ứng dụng quản lý thư viện.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_ly_danh_sch_sch(self) -> None:
        """Test case for ly_danh_sch_sch

        Lấy danh sách sách
        """
        pass

    def test_ly_thng_tin_sch(self) -> None:
        """Test case for ly_thng_tin_sch

        Lấy thông tin sách
        """
        pass

    def test_thm_sch_mi(self) -> None:
        """Test case for thm_sch_mi

        Thêm sách mới
        """
        pass

    def test_xa_sch(self) -> None:
        """Test case for xa_sch

        Xóa sách
        """
        pass


if __name__ == '__main__':
    unittest.main()
