# coding: utf-8

"""
    Library Management API

    API cho ứng dụng quản lý thư viện.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.lyth_ng_tin_sch200_response import LYThNgTinSCh200Response

class TestLYThNgTinSCh200Response(unittest.TestCase):
    """LYThNgTinSCh200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LYThNgTinSCh200Response:
        """Test LYThNgTinSCh200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LYThNgTinSCh200Response`
        """
        model = LYThNgTinSCh200Response()
        if include_optional:
            return LYThNgTinSCh200Response(
                id = '',
                title = '',
                author = '',
                year = 1.337
            )
        else:
            return LYThNgTinSCh200Response(
        )
        """

    def testLYThNgTinSCh200Response(self):
        """Test LYThNgTinSCh200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
