# coding: utf-8

# flake8: noqa
"""
    Product and Store Management API

    A simple API for managing products and stores with basic CRUD operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.product import Product
from openapi_client.models.product_input import ProductInput
from openapi_client.models.store import Store
from openapi_client.models.store_input import StoreInput

