# coding: utf-8

"""
    Library Management API

    API cho ứng dụng quản lý thư viện.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Library Management API",
    description="API cho ứng dụng quản lý thư viện.",
    version="",
)

app.include_router(DefaultApiRouter)
